[Partition]
Type=usr-verity
# Empty B verity slot -- see 40-usr-b.conf. sysupdate writes data+hash+sig
# together into the empty B set on the first update.
Label=_empty
SizeMinBytes=64M
SizeMaxBytes=64M
Verity=hash
VerityMatchKey=usr-b
