[Partition]
Type=usr-verity-sig
# Ancient-dummy-version B verity-sig slot -- see 40-usr-b.conf. Matches
# MatchPattern=archetype_@v_verity_sig, sorts oldest.
Label=archetype_1970.01.01-1_verity_sig
Verity=signature
VerityMatchKey=usr-b
